version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/js-yaml"
    versions:
    - 4.0.0
  - dependency-name: js-yaml
    versions:
    - 4.0.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 3.7.0
  - dependency-name: eslint
    versions:
    - 7.5.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 3.7.0
  - dependency-name: typescript
    versions:
    - 3.9.7
  - dependency-name: eslint-plugin-eslint-plugin
    versions:
    - 2.3.0
