name: CI
on:
  - push
  - pull_request

jobs:
  Test:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - node: [11, 12, 14]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run tests 👩🏾‍💻
        run: |
          npm run test-link
          npm run test

      - name: Lint ✨
        run: npm run lint
