apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-ingress
  namespace: space
spec:
  rules:
    - host: hostname.com
      http:
        paths:
          - backend:
              serviceName: service
              servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: service-ingress-nonlive
  namespace: space
spec:
  rules:
    - host: hostname-nonlive.com
      http:
        paths:
          - backend:
              serviceName: service-b
              servicePort: 80
